---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    app: apiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
      - name: apiservice
        image: aspire/apiservice:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: apiservice-env
        resources:
          requests:
            memory: "256Mi"  # 256 Mebibytes of memory
            cpu: "250m"      # 0.25 CPU
          limits:
            memory: "512Mi"  # 512 Mebibytes of memory
            cpu: "500m"      # 0.5 CPU