apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: aspire

resources:
- apiservice
- webfrontend
- namespace.yaml
- dashboard.yaml

generatorOptions:
  disableNameSuffixHash: true


