name: Deploy Aspire to ACA

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      ACA_APP_NAME: ""
      ACA_RESOURCE_GROUP: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK 9.0.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh

      - name: Set Subscription ID and Location
        working-directory: ./src/Aspire/Aspire.AppHost
        run: |
          azd config set defaults.subscription ${{ env.AZURE_SUBSCRIPTION_ID }}
          azd config set defaults.location ${{ env.AZURE_LOCATION }}

      - name: Provision Infrastructure
        working-directory: ./src/Aspire/Aspire.AppHost
        run: azd provision --environment ${{ env.AZURE_ENV_NAME }} --no-prompt

      - name: Extract ACA App Name and Resource Group
        id: extract-aca-vars
        working-directory: ./src/Aspire/Aspire.AppHost
        run: |
          azd env get-values --environment ${{ env.AZURE_ENV_NAME }} > .env.tmp
          source .env.tmp
          echo "ACA_APP_NAME=$CONTAINERAPPS_NAME" >> $GITHUB_ENV
          echo "ACA_RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_ENV

      - name: Set ACA Secret from GitHub Secret
        run: |
          az containerapp secret set \
            --name ${{ env.ACA_APP_NAME }} \
            --resource-group ${{ env.ACA_RESOURCE_GROUP }} \
            --secrets AzureAd__ClientSecret=${{ secrets.AZUREAD_CLIENT_SECRET }}

      - name: Map ACA Secret to Environment Variable
        run: |
          az containerapp update \
            --name ${{ env.ACA_APP_NAME }} \
            --resource-group ${{ env.ACA_RESOURCE_GROUP }} \
            --set-env-vars AzureAd__ClientSecret=secretref:AzureAd__ClientSecret

      - name: Deploy Application
        working-directory: ./src/Aspire/Aspire.AppHost
        run: azd deploy --environment ${{ env.AZURE_ENV_NAME }} --all --no-prompt