name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh

      - name: Set Subscription ID
        working-directory: ./src/Aspire/Aspire.AppHost
        run: azd config set defaults.subscription ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        working-directory: ./src/Aspire/Aspire.AppHost
        run: azd provision --environment ${{ env.AZURE_ENV_NAME }} --no-prompt

      - name: Deploy Application
        working-directory: ./src/Aspire/Aspire.AppHost
        run: azd deploy --environment ${{ env.AZURE_ENV_NAME }} --no-prompt